#!/bin/bash

thread () 
{ 
   local i;
   date;
   while ((++i)); do
      sleep $((5-$(date +%s)%5));
      echo "$BASHPID $i $(date)";
   done
}
jkill () 
{ 
   local jx
   for j in $(jobs|sed 's/^\[\([0-9]*\).*/\1/g')
   do
      jx+="%$j "
   done
   kill $jx
}
