#!/bin/bash
#fast-detect host from list (sizeof any) with the best response
#example: best=$(./top_ping); echo $best

rm -rf /tmp/*.-ping

#linux or cygwin?
cw=false
if which cygpath 2>&1 > /dev/null
then cw=true
fi

for h in aquarius-{va,bg,den,dae} {amazon,yahoo,softwareag,ebay,googleQWERT,youtube}.com {pscu,gnu}.org localhost
do
   while true; do test $(jobs|wc -l) -gt 100 && sleep 1 || break; done #throttle
   ping -$($cw && echo n || echo c) 4 -w 3 $h > /tmp/$h.-ping 2>&1&    #parallel
done; wait

#when in doubt, use brute force ~ken
grep "time[=<][^ ]\+" /tmp/*.-ping -o|sort -t '=' -k2n 1>&2
grep "time[=<][^ ]\+" /tmp/*.-ping -o|sort -t '=' -k2n |head -1|sed 's~/tmp/\(.*\)\.-ping.*~\1~'

#warn on failed probes
(grep 'could not find\|unknown host\|timed out'\
   /tmp/*.-ping && echo warn: failed on some hosts above ||:) 1>&2

