#!/bin/bash

#quick detect host with best response
rm -rf /tmp/*.-ping

#linux or cygwin?
cw=false
if which cygpath 2>&1 > /dev/null
then cw=true
fi

for h in aquarius-{va,bg,den,dae} {amazon,yahoo,softwareag,ebay,googleqwert,youtube.com}.com {pscu,gnu}.org
do
   ping -$($cw && echo n || echo c) 3 -w 3 $h > /tmp/$h.-ping 2>&1& #&find fast!
done; wait

#unix brute force in action when in doubt
grep "time=[^ ]\+" /tmp/*.-ping -o|sort -t '=' -k2n 1>&2
grep "time=[^ ]\+" /tmp/*.-ping -o|sort -t '=' -k2n |head -1|sed 's~/tmp/\(.*\)\.-ping.*~\1~'

#test -s /tmp/duh.-ping && { echo 'warn $0: some host(s) do not response' 1>&2; } ||:

#warn on failed probes
(grep 'could not find\|unknown host'\
   /tmp/*.-ping && echo warn: no response on some hosts above ||:) 1>&2

